### ISSUE TITLE
A 75% keyboard would be amazing.

### ISSUE THREAD

**Issue by zandegran** [MakotoKurauchi/helix#14] opened 2019-01-25 08:57 UTC
Most of the European languages have additional characters and a 75% keyboard would have enough keys to accommodate dedicated keys for those, without having to change the keyboard layout. Another use case can be developers can have dedicated keys for {}() to make life lot easier.

Even without these a 75% keyboard would be a nice addition.

**Comment by culturalsnow** [comment] 2019-01-26 10:31
Can see your point, but not sure if this counts as an issue for the Helix keyboard itself?

**Comment by theAkito** [comment] 2020-01-22 21:53
If the Helix would be a full-size keyboard like e.g. the BFO-9000, I would immediately start building it. The problem is all the hype about these tiny keyboards...

@culturalsnow Yes, it is an issue with the Helix keyboard, because it is too small. If the PCB would be bigger, then you could still break off rows that you don't need. Whereas if the PCB is too small in the first place, then you hardly can attach new rows...

**Comment by MakotoKurauchi** [comment] 2020-01-28 02:21
This is not a Helix keyboard issue. 
I close this issue.

**Closed by MakotoKurauchi** 2020-01-28 02:21 UTC

**Comment by zeljkot** [comment] 2020-05-25 09:29
7 x 7 (+1) Helix would be great for both ISO layout and programming.
